---
- name: all tasks
  hosts: all
  tasks:
     - name: install packages
       package:
         name: "{{ packages }}"
       vars:
         packages:
         - emacs
         - audacious-plugins-exotic
         - audacious-plugins-freeworld
         - audacious
         - mpv
         - vlc
         - neovim
         - projectM-pulseaudio
         - podman
         - pandoc
         - remmina-plugins-rdp
         - remmina-plugins-spice
     - name: install flatpaks
       flatpak:
         name: "{{ flatpaks }}"
       vars:
         flatpaks:
         - org.chromium.Chromium
         - com.slack.Slack
         - com.discordapp.Discord
         - org.mozilla.firefox
         - org.signal.Signal
         - org.telegram
     - name: install yum groups
       yum:
         name: "{{ yum_groups }}"
       vars:
         yum_groups:
         - "@development-tools"
         - "@virtualization"
